# This is a basic workflow to help you get started with Actions
name: Build Check

# Controls when the workflow will run
on:
  push:
    branches:
      - "**"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Install compiler and build tools needed for compilation
    steps:
      - name: install-build-essential
        run: sudo apt-get update && sudo apt-get -y install build-essential

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3

      # Compile the project using the make command
      - name: build
        run: make

      # unit test
      - name: unit test
        run: make test
